In [1]:
import pandas as pd
import statsmodels.formula.api as smf

In [2]:
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/Midterm Election Project/Midterm Elections Model #1 Sept 4.csv'
df = pd.read_csv(file_path)

Mounted at /content/drive

In [3]:
df_train = df[df["Year"] < 2026]
df_train

,Year,State,Poll_Margin,Dem_Incumbent,Rep_Incumbent,Partisan_Lean,Midterm,President_Party,Special_Election,Class,Result,Actual_Margin
9,2024,Wisconsin,1.8,1,0,-2,0,1,0,1,1.0,0.9
10,2024,Michigan,2.3,0,0,-1,0,1,0,1,1.0,0.3
11,2024,Pennsylvania,1.8,1,0,-2,0,1,0,1,0.0,-0.2
12,2024,Ohio,-1.7,1,0,-6,0,1,0,1,0.0,-3.6
13,2024,Texas,-4.4,0,1,-5,0,1,0,1,0.0,-4.4
14,2024,Arizona,2.6,0,0,-2,0,1,0,1,1.0,2.4
15,2024,Nevada,4.9,1,0,-1,0,1,0,1,1.0,1.7
16,2022,Wisconsin,-3.6,0,1,-2,1,1,0,3,0.0,-1.0
17,2022,Pennsylvania,-0.4,0,0,-2,1,1,0,3,1.0,4.9
18,2022,Georgia,-1.4,1,0,-3,1,1,0,3,1.0,0.9
19,2022,Arizona,-0.3,1,0,-2,1,1,0,3,1.0,4.9
20,2022,Nevada,-3.4,1,0,-1,1,1,0,3,1.0,0.9
21,2022,Ohio,-8.0,0,0,-6,1,1,0,3,0.0,-6.5
22,2022,North Carolina,-6.2,0,0,-3,1,1,0,3,0.0,-3.2
23,2020,Michigan,5.4,1,0,1,0,0,0,2,1.0,1.7
24,2020,Maine,4.5,0,1,3,0,0,0,2,0.0,-8.6
25,2020,North Carolina,2.6,0,1,-3,0,0,0,2,0.0,-1.8
26,2020,Iowa,-1.4,0,1,-3,0,0,0,2,0.0,-6.6
27,2020,Arizona,5.7,0,1,-5,0,0,1,3,1.0,2.4
28,2020,Georgia,2.8,0,1,-5,0,0,0,2,1.0,1.2
29,2020,Georgia,2.8,0,1,-5,0,0,1,3,1.0,2.0
30,2018,Missouri,-0.6,1,0,-9,1,0,0,1,0.0,-6.0
31,2018,Indiana,0.7,1,0,-9,1,0,0,1,0.0,-5.9
32,2018,West Virginia,5.0,1,0,-19,1,0,0,1,1.0,3.2
33,2018,Florida,2.4,1,0,-2,1,0,0,1,0.0,-0.2
34,2018,Arizona,-1.0,0,0,-5,1,0,0,1,1.0,2.3
35,2018,Nevada,0.0,0,1,1,1,0,0,1,1.0,5.0
36,2018,Montana,3.3,1,0,-11,1,0,0,1,1.0,3.1
37,2018,Tennessee,-5.1,0,0,-14,1,0,0,1,0.0,-10.8
38,2016,Wisconsin,2.7,0,1,2,0,1,0,3,0.0,-3.4
39,2016,Pennsylvania,2.0,0,1,1,0,1,0,3,0.0,-1.6
40,2016,New Hampshire,-1.5,0,1,1,0,1,0,3,1.0,0.2
41,2016,North Carolina,-2.0,0,1,-3,0,1,0,3,0.0,-5.7
42,2016,Missouri,-1.3,0,1,-5,0,1,0,3,0.0,-2.8
43,2016,Nevada,1.8,0,0,2,0,1,0,3,1.0,2.4
44,2014,New Hampshire,0.8,1,0,1,1,1,0,2,1.0,3.2
45,2014,Georgia,3.0,0,0,-6,1,1,0,2,0.0,-7.9
46,2014,Iowa,-2.3,0,0,1,1,1,0,2,0.0,-8.5
47,2014,Colarado,-2.5,1,0,1,1,1,0,2,0.0,-2.5
48,2014,Alaska,-2.4,1,0,-13,1,1,0,2,0.0,-2.2

In [4]:
df_test = df[df["Year"] == 2026]
df_test

,Year,State,Poll_Margin,Dem_Incumbent,Rep_Incumbent,Partisan_Lean,Midterm,President_Party,Special_Election,Class,Result,Actual_Margin
0,2026,Texas,2.4,0,0,-6,1,0,0,2,NaN,NaN
1,2026,North Carolina,8.0,0,0,-1,1,0,0,2,NaN,NaN
2,2026,Maine,2.3,0,1,4,1,0,0,2,NaN,NaN
3,2026,Ohio,2.6,0,1,-5,1,0,1,3,NaN,NaN
4,2026,Michigan,-0.3,0,0,0,1,0,0,2,NaN,NaN
5,2026,Iowa,-1.8,0,0,-6,1,0,0,2,NaN,NaN
6,2026,Alaska,2.0,0,1,-6,1,0,0,2,NaN,NaN
7,2026,Georgia,7.5,1,0,-1,1,0,0,2,NaN,NaN
8,2026,New Hampshire,2.0,0,0,2,1,0,0,2,NaN,NaN

In [5]:
log_model = smf.logit("Result ~ Poll_Margin + Partisan_Lean + President_Party + Midterm + Dem_Incumbent + Rep_Incumbent", data = df_train).fit()
log_model.summary()

Optimization terminated successfully.
         Current function value: 0.560402
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 Result   No. Observations:                   40
Model:                          Logit   Df Residuals:                       33
Method:                           MLE   Df Model:                            6
Date:                Sat, 05 Sep 2026   Pseudo R-squ.:                  0.1901
Time:                        01:33:38   Log-Likelihood:                -22.416
converged:                       True   LL-Null:                       -27.676
Covariance Type:            nonrobust   LLR p-value:                    0.1044
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.3747      1.543      0.243      0.808      -2.650       3.399
Poll_Margin         0.3639      0.172      2.118      0.034       0.027       0.701
Partisan_Lean       0.0741      0.097      0.765      0.444      -0.116       0.264
President_Party    -0.0582      1.042     -0.056      0.955      -2.101       1.985
Midterm             0.4231      1.075      0.394      0.694      -1.684       2.530
Dem_Incumbent      -0.2801      0.969     -0.289      0.773      -2.180       1.620
Rep_Incumbent      -1.2543      1.206     -1.040      0.298      -3.618       1.109
===================================================================================
"""

In [6]:
df_test["Prediction"] = log_model.predict(df_test)

/tmp/ipykernel_1514/98102598.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test["Prediction"] = log_model.predict(df_test)

In [7]:
df_test

,Year,State,Poll_Margin,Dem_Incumbent,Rep_Incumbent,Partisan_Lean,Midterm,President_Party,Special_Election,Class,Result,Actual_Margin,Prediction
0,2026,Texas,2.4,0,0,-6,1,0,0,2,NaN,NaN,0.773220
1,2026,North Carolina,8.0,0,0,-1,1,0,0,2,NaN,NaN,0.974294
2,2026,Maine,2.3,0,1,4,1,0,0,2,NaN,NaN,0.663026
3,2026,Ohio,2.6,0,1,-5,1,0,1,3,NaN,NaN,0.529747
4,2026,Michigan,-0.3,0,0,0,1,0,0,2,NaN,NaN,0.665653
5,2026,Iowa,-1.8,0,0,-6,1,0,0,2,NaN,NaN,0.425105
6,2026,Alaska,2.0,0,1,-6,1,0,0,2,NaN,NaN,0.456779
7,2026,Georgia,7.5,1,0,-1,1,0,0,2,NaN,NaN,0.959803
8,2026,New Hampshire,2.0,0,0,2,1,0,0,2,NaN,NaN,0.842079